### PR TITLE
Avoid removal of default_schema when default_schema is None

### PR DESCRIPTION
**Pull request by Jakalman**
I'm not sure if this is intended behavior or not

### CODE REVIEW

**Comment by zzzeek** [comment]
where are you observing a problem here?   backend, configuration, etc.    this at least needs a unit test as well.

**Comment by Jakalman** [comment]
The problem I encountered is that when running alembic to autogenerate database migrations with include_schemas=True, alembic would not recognize existing tables in the database, and would issue create statements for all of them. I believe this is because the schemas set was empty (as a result of the `schemas.add(None);
schemas.discard(default_schema)`
lines)

**Comment by zzzeek** [comment]
i understand that, but nobody has ever reported such an issue nor have I seen it happen.  it has to be reproducible.    more details are needed

**Comment by Jakalman** [comment]
No problem

**Comment by zzzeek** [comment]
why did you close this?

**Comment by Jakalman** [comment]
Trying to create easily reproducible conditions

**Comment by zzzeek** [comment]
dont worry, I figured something close enough out fix is going through at https://gerrit.sqlalchemy.org/#/c/131/

**Comment by Jakalman** [comment]
sorry about the weird format

**Pull request closed without merging**
