### PR TITLE
Fix postgresql automigration for ARRAY types

### PR DESCRIPTION
**Pull request by pbrackin**

### CODE REVIEW

**Comment by zzzeek** [comment]
hmmm, looks like you've done all the things!   pretty nice.   dealing w/ 1ft of snow here so will try to get to merging this soon thanks!

**Comment by pbrackin** [comment]
OK great.  Glad I could help out.  Good luck with that snow!

**Comment by zzzeek** [comment]
pulling into gerrit.

**Comment by zzzeek** [comment]
Dear contributor -

This pull request is being moved to Gerrit, at https://gerrit.sqlalchemy.org/313, where it may be tested and reviewed more closely.  As such, the pull request itself is being marked "closed" or "declined", however your contribution is merely being moved to our central review system. Please register at https://gerrit.sqlalchemy.org#/register/ to send and receive comments regarding this item.

**Pull request closed without merging**
