### PR TITLE
add support to pass migration_script into revision command

### PR DESCRIPTION
**Pull request by tysonholub**
allows a migration_script to be passed into revision command without an environment such that a module could generate migrations against a project programmatically.

Ex:
```python
from alembic import command
from alembic.config import Config
from alembic.operations import ops
import sqlalchemy as sa
import os

config = Config(os.environ['ALEMBIC_CONFIG'])

migration_script = ops.MigrationScript(
    rev_id=None,
    upgrade_ops=ops.UpgradeOps(
        ops=[
            ops.CreateTableOp(
                'test_table',
                [
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('name', sa.String(50), nullable=False)
                ]
            ),
        ]
    ),
    downgrade_ops=ops.DowngradeOps(
        ops=[
            ops.DropTableOp('test_table')
        ]
    ),
)

command.revision(config, message='add test table', migration_script=migration_script)
```

### CODE REVIEW

**Comment by zzzeek** [comment]
Hi there -

So, I agree with the use case here, given a MigrationScript, generate the Python file.  Great idea.   But APIwise there's already an appropriate place to add this, which is the [render_python_code](https://github.com/zzzeek/alembic/blob/master/alembic/autogenerate/api.py#L137) helper function created just for this purpose.   Right now it accepts UpgradeOps or DowngradeOps, it can be made to also accept a whole MigrationScript in which case it will do what you have it doing here.    I'd not pull in "command" (where everything has to have meaning on the commandline) and render_python_code already handles the case of the "quick default environment".

**Comment by tysonholub** [comment]
Ok, thanks for the feedback. I will investigate reworking the render_python_code function for this purpose. On another note, what is your solution for supporting multiple model files with autogenerate functionality?

**Comment by zzzeek** [comment]
multiple "files" does not imply there'd be more than one declarative "Base" with a single MetaData in it.  Usually the whole model for an application shares one MetaData across the whole thing.  That said, if you have multiple MetaData objects there's a feature add for this but in the interim you can merge the tables within them together into a new MetaData within your environment using table.to_metadata(some_metadata):
  
    my_metadata = MetaData()
    for meta in my_existing_metadatas:
        for table in meta.tables.values():
            table.tometadata(my_metadata)

**Comment by zzzeek** [comment]
see https://bitbucket.org/zzzeek/alembic/issues/38/allow-multiple-metadata-objects-for

**Pull request closed without merging**
