### PR TITLE
add comparison for DateTime.timezone

### PR DESCRIPTION
**Pull request by davidszotten**

### CODE REVIEW

**Comment by zzzeek** [comment]
nice!  ill try to get this in soon.  hopefully this one won't blow up openstack test suites.

**Comment by davidszotten** [comment]
hey, any updates on this? how did openstack fare?

**Comment by zzzeek** [comment]
i have about 15 PRs to get through and am getting back on track after a week of travel.   this one is in the middle of the list.

**Comment by davidszotten** [comment]
cool, thanks for the update!

**Comment by zzzeek** [comment]
Dear contributor -

This pull request is being moved to Gerrit, at https://gerrit.sqlalchemy.org/123, where it may be tested and reviewed more closely.  As such, the pull request itself is being marked "closed" or "declined", however your contribution is merely being moved to our central review system. Please register at https://gerrit.sqlalchemy.org#/register/ to send and receive comments regarding this item.

**Pull request closed without merging**
